"""Project-level constants used by bootstrap and UI helpers."""

DEFAULT_ADMIN_USER_ID = "00000000"
DEFAULT_ADMIN_USERNAME = "admin"
DEFAULT_ADMIN_REAL_NAME = "系统管理员"
DEFAULT_ADMIN_PASSWORD = "123456"

ROLE_SUPER_ADMIN = "超级管理员"
ROLE_ADMIN = "管理端基础角色"
ROLE_USER = "普通用户基础角色"

NAV_DIRECTORY = "目录"
NAV_USER = "用户"
NAV_APPLICATION = "应用"
NAV_INFORMATION = "信息"

DEFAULT_ROLE_MAPPINGS = {
    ROLE_SUPER_ADMIN: [NAV_DIRECTORY, NAV_USER, NAV_APPLICATION, NAV_INFORMATION],
    ROLE_ADMIN: [NAV_DIRECTORY, NAV_USER, NAV_APPLICATION, NAV_INFORMATION],
    ROLE_USER: [NAV_DIRECTORY],
}

APPROVAL_PENDING = 0
APPROVAL_APPROVED = 1
APPROVAL_REJECTED = 2
APPROVAL_DISABLED = 3

STATUS_TEXT_MAP = {
    0: "否",
    1: "是",
}

EXAMPLE_DIRECTORY_NAME = "示例插件"
EXAMPLE_DIRECTORY_DESCRIPTION = "用于初始化、联调和插件加载验证的示例目录。"
EXAMPLE_APP_VERSION_DESCRIPTION = "示例插件预置版本"
